---
ci:
  # format compatible with commitlint
  autoupdate_commit_msg: "chore: pre-commit autoupdate"
  autoupdate_schedule: monthly
  autofix_commit_msg: "chore: auto fixes from pre-commit.com hooks"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycontribs/mirrors-prettier
    rev: v3.3.2
    hooks:
      - id: prettier
        always_run: true
        additional_dependencies:
          - prettier
          - prettier-plugin-toml
          - prettier-plugin-sort-json

  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: 1.3.1
    hooks:
      - id: tox-ini-fmt

  - repo: local
    hooks:
      - id: dictionary-clean
        name: clean up cspell dictionary
        entry: python3
        args:
          - -c
          - |
            from pathlib import Path
            f = Path(".config/dictionary.txt")
            f.write_text("\n".join(sorted(set(f.read_text().lower().splitlines())))+"\n")
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: check-broken-links
        name: check for broken markdown links
        entry: python3
        args:
          - check_relative_links.py
        language: system
        pass_filenames: false
