---
name: preview

permissions:
  contents: write
  pull-requests: write

concurrency: preview-${{ github.ref }}

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - closed

env:
  CONTAINER_RUNTIME: docker
  RUN_CMD: >-
    QUARTZ_BUILD_OPTS='-o /repo/public' make -f /repo/Makefile public

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: github.event.action != 'closed'
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
          fetch-depth: 0

      - name: Build site
        if: github.event.action != 'closed'
        run: make run

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: public

      - name: Update preview comment with note about being patient
        if: github.event.action != 'closed'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-preview
          append: true
          message: |
            > [!IMPORTANT]
            > The link above will not work until the Pages deployment is complete. You can find this under [Actions -> pages-build-deployment](https://github.com/andyettanotherorg/shanemcd.github.io/actions/workflows/pages/pages-build-deployment).
